### ISSUE TITLE
can't select conversation agent

### ISSUE THREAD

**Issue by gretel** [Shulyaka/anthropic-hass#2]
setup seems fine.. am i doing something wrong here? regards
![image](https://github.com/user-attachments/assets/eb6f8851-f5b4-42b9-84be-38dccf5def9c)
![image](https://github.com/user-attachments/assets/29ef0764-bb6a-4d22-b504-9d1861c589e7)
![image](https://github.com/user-attachments/assets/05221af5-3377-4c80-bf4b-6f4decc4f4a5)

**Comment by Shulyaka** [comment]
Hi! The component is based on pre-release version of Home Assistant. It will work once HA 2024.8.0 is released (or in the current development version). Sorry for the inconvenience!

**Comment by Shulyaka** [comment]
I can fix that...

**Comment by Shulyaka** [comment]
Should be compatible with HA 2024.7 now, please update the component

**Comment by gretel** [comment]
> Should be compatible with HA 2024.7 now, please update the component

![image](https://github.com/user-attachments/assets/d122e9d7-6317-4228-a1ed-b1f46947973b)
